// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TFM_Manager.Data.DbContext;

#nullable disable

namespace TFM_Manager.Data.Migrations
{
    [DbContext(typeof(TfmManagerDbContext))]
    partial class TfmManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RegisteredAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RepresentativeEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("RepresentativeEmployeeId");

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.CompanyAccountingContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyAccountingContacts");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.CompanyBankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("SWIFTBIC")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1 AND [IsDefault] = 1");

                    b.ToTable("CompanyBankAccounts");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.CompanyDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("CompanyDocuments");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.EmployeeDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("EmployeeDocuments");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.PartnerContactDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PartnerContactId")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PartnerContactId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PartnerContactDocuments");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.PartnerDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PartnerId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PartnerDocuments");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.PartnerLocationDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PartnerLocationId")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("PartnerLocationId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("PartnerLocationDocuments");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.CompanyEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("EmploymentTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmploymentTypeId");

                    b.HasIndex("CompanyId", "EmployeeId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("CompanyEmployees");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.CompanyEmployeeSalary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyEmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("EmployeeContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EmployerContribution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal>("TotalCompanyCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.Property<int>("WorkTimeTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyEmployeeId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("WorkTimeTypeId");

                    b.ToTable("CompanyEmployeeSalaries");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MotherName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfBirth")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SocialSecurityNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxIdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("TaxIdentificationNumber")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserRoleId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Közös képviselő"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Számvizsgáló"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Pénzügyi kapcsolattartó"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Műszaki kapcsolattartó"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Gondnok"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Lakó"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Tulajdonos"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Irodai kapcsolattartó"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Szerződés"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Megrendelő"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Teljesítésigazolás"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Jegyzőkönyv"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Cégkivonat"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Aláírási címpéldány"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "NAV dokumentum"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Banki dokumentum"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Személyi igazolvány"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Lakcímkártya"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Adókártya"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "TAJ kártya"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "Munkaszerződés"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "Orvosi alkalmassági"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.EmployeeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Normál dolgozó"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Képviselő"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Vezető"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Adminisztratív munkatárs"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Külsős"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Alvállalkozó"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.EmploymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EmploymentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Munkaviszony"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Egyszerűsített foglalkoztatás"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Megbízási jogviszony"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Alvállalkozó"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Ügyvezető"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Tulajdonos"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Alapadatok"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Tasks"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Számlázás"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Riportok"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "User kezelés"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Törzsadatok"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.PartnerLocationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PartnerLocationTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Épület"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Lépcsőház"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Garázs"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Porta"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Udvar / kert"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Tároló"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Gépészeti helyiség"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Hulladéktároló"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.PartnerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PartnerTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Társasház"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Magánszemély"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Gazdasági társaság"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Intézmény"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.RoleModulePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanCreate")
                        .HasColumnType("bit");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("CanEdit")
                        .HasColumnType("bit");

                    b.Property<bool>("CanView")
                        .HasColumnType("bit");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("UserRoleId", "ModuleId")
                        .IsUnique();

                    b.ToTable("RoleModulePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            ModuleId = 2,
                            UserRoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 1,
                            UserRoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 2,
                            UserRoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 1,
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 5,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 2,
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 3,
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            ModuleId = 4,
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            ModuleId = 6,
                            UserRoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 1,
                            UserRoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 2,
                            UserRoleId = 4
                        },
                        new
                        {
                            Id = 11,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 3,
                            UserRoleId = 4
                        },
                        new
                        {
                            Id = 12,
                            CanCreate = false,
                            CanDelete = false,
                            CanEdit = false,
                            CanView = true,
                            ModuleId = 4,
                            UserRoleId = 4
                        },
                        new
                        {
                            Id = 13,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 5,
                            UserRoleId = 4
                        },
                        new
                        {
                            Id = 14,
                            CanCreate = true,
                            CanDelete = false,
                            CanEdit = true,
                            CanView = true,
                            ModuleId = 6,
                            UserRoleId = 4
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Takarítás"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Gondnokság"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Kertészet"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Portaszolgálat"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Karbantartás"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Eseti munka"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Garázstakarítás"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Hibaelhárítás"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Dolgozó"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Vezető"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.WorkTimeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DailyHours")
                        .HasColumnType("decimal(4,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("WorkTimeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DailyHours = 2.00m,
                            IsActive = true,
                            Name = "Napi 2 óra"
                        },
                        new
                        {
                            Id = 2,
                            DailyHours = 4.00m,
                            IsActive = true,
                            Name = "Napi 4 óra"
                        },
                        new
                        {
                            Id = 3,
                            DailyHours = 6.00m,
                            IsActive = true,
                            Name = "Napi 6 óra"
                        },
                        new
                        {
                            Id = 4,
                            DailyHours = 8.00m,
                            IsActive = true,
                            Name = "Napi 8 óra"
                        },
                        new
                        {
                            Id = 5,
                            DailyHours = 0.00m,
                            IsActive = true,
                            Name = "Egyéb"
                        });
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BillingName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MailingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PartnerTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("PartnerTypeId");

                    b.ToTable("Partners");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("ContractFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("ContractStartDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("PartnerId", "CompanyId", "ServiceTypeId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("PartnerCompanies");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PartnerContacts");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LocationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("PartnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationTypeId");

                    b.HasIndex("PartnerId");

                    b.ToTable("PartnerLocations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.Company", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Employees.Employee", "RepresentativeEmployee")
                        .WithMany("RepresentedCompanies")
                        .HasForeignKey("RepresentativeEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RepresentativeEmployee");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.CompanyAccountingContact", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Companies.Company", "Company")
                        .WithMany("AccountingContacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.CompanyBankAccount", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Companies.Company", "Company")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.CompanyDocument", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Companies.Company", "Company")
                        .WithMany("Documents")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Lookups.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("DocumentType");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.EmployeeDocument", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Employees.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Employee");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.PartnerContactDocument", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Partners.PartnerContact", "PartnerContact")
                        .WithMany("Documents")
                        .HasForeignKey("PartnerContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("PartnerContact");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.PartnerDocument", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Partners.Partner", "Partner")
                        .WithMany("Documents")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Partner");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Documents.PartnerLocationDocument", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Partners.PartnerLocation", "PartnerLocation")
                        .WithMany("Documents")
                        .HasForeignKey("PartnerLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Identity.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("PartnerLocation");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.CompanyEmployee", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Companies.Company", "Company")
                        .WithMany("CompanyEmployees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Employees.Employee", "Employee")
                        .WithMany("CompanyEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Lookups.EmploymentType", "EmploymentType")
                        .WithMany()
                        .HasForeignKey("EmploymentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Employee");

                    b.Navigation("EmploymentType");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.CompanyEmployeeSalary", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Employees.CompanyEmployee", "CompanyEmployee")
                        .WithMany("Salaries")
                        .HasForeignKey("CompanyEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Lookups.WorkTimeType", "WorkTimeType")
                        .WithMany()
                        .HasForeignKey("WorkTimeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompanyEmployee");

                    b.Navigation("WorkTimeType");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.Employee", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Employees.Employee", "Employee")
                        .WithOne("ApplicationUser")
                        .HasForeignKey("TFM_Manager.Data.Entities.Identity.ApplicationUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Lookups.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.RoleModulePermission", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Lookups.UserRole", "UserRole")
                        .WithMany("Permissions")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.Partner", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.PartnerType", "PartnerType")
                        .WithMany()
                        .HasForeignKey("PartnerTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartnerType");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerCompany", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Companies.Company", "Company")
                        .WithMany("PartnerCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Partners.Partner", "Partner")
                        .WithMany("PartnerCompanies")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Lookups.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Partner");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerContact", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Partners.Partner", "Partner")
                        .WithMany("Contacts")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ContactType");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerLocation", b =>
                {
                    b.HasOne("TFM_Manager.Data.Entities.Lookups.PartnerLocationType", "LocationType")
                        .WithMany()
                        .HasForeignKey("LocationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TFM_Manager.Data.Entities.Partners.Partner", "Partner")
                        .WithMany("Locations")
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocationType");

                    b.Navigation("Partner");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Companies.Company", b =>
                {
                    b.Navigation("AccountingContacts");

                    b.Navigation("BankAccounts");

                    b.Navigation("CompanyEmployees");

                    b.Navigation("Documents");

                    b.Navigation("PartnerCompanies");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.CompanyEmployee", b =>
                {
                    b.Navigation("Salaries");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Employees.Employee", b =>
                {
                    b.Navigation("ApplicationUser");

                    b.Navigation("CompanyEmployees");

                    b.Navigation("Documents");

                    b.Navigation("RepresentedCompanies");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Lookups.UserRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.Partner", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Documents");

                    b.Navigation("Locations");

                    b.Navigation("PartnerCompanies");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerContact", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("TFM_Manager.Data.Entities.Partners.PartnerLocation", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
