<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>TFM_Manager.Data</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\Identity\" />
    <Folder Include="Entities\Companies\" />
    <Folder Include="Entities\Employees\" />
    <Folder Include="Entities\Documents\" />
    <Folder Include="Entities\Lookups\" />
    <Folder Include="Entities\Partners\" />
    <Folder Include="DbContext\" />
    <Folder Include="Migrations\" />
    <Folder Include="Seed\" />
  </ItemGroup>

</Project>
